# Generated by Django 6.0.3 on 2026-05-07 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='video',
            name='users_with_access',
            field=models.ManyToManyField(blank=True, related_name='unlocked_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
