# Generated by Django 6.0.3 on 2026-04-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_video_url_video_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['season_number', 'episode_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Episodio'),
        ),
        migrations.AddField(
            model_name='video',
            name='season_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Temporada'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='videos.category')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='videos.serie'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('serie', 'season_number', 'episode_number')},
        ),
    ]
