# Generated by Django 6.0.3 on 2026-05-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
