# Generated by Django 6.0.3 on 2026-07-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tokens',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
